# Generated by Django 4.0.4 on 2022-06-03 18:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FormData',
            fields=[
                ('id', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('form_id', models.IntegerField(null=True)),
                ('field_id', models.IntegerField(null=True)),
                ('value', models.CharField(max_length=100)),
                ('record_id', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='FormModel',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='FormRecord',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Participants',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('favorite_book', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='FormField',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('label', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=100)),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forms.formmodel')),
            ],
        ),
    ]
