# Generated by Django 4.0.4 on 2022-06-05 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='participants',
            name='birthday',
            field=models.DateField(null=True),
        ),
    ]
