# Generated by Django 4.0.4 on 2022-06-05 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0003_rename_favorite_book_participants_favorite_lang'),
    ]

    operations = [
        migrations.RenameField(
            model_name='participants',
            old_name='favorite_lang',
            new_name='favorite_book',
        ),
    ]
