# Generated by Django 4.0.4 on 2022-06-05 12:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0004_rename_favorite_lang_participants_favorite_book'),
    ]

    operations = [
        migrations.RenameField(
            model_name='participants',
            old_name='favorite_book',
            new_name='favorite_lang',
        ),
    ]
